# Generated by Django 5.0.6 on 2024-06-08 11:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Scrapping_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.CharField(blank=True, max_length=100, null=True)),
                ('price_change', models.CharField(blank=True, max_length=100, null=True)),
                ('market_cap', models.CharField(blank=True, max_length=100, null=True)),
                ('market_cap_rank', models.CharField(blank=True, max_length=100, null=True)),
                ('volume', models.CharField(blank=True, max_length=100, null=True)),
                ('volume_rank', models.CharField(blank=True, max_length=100, null=True)),
                ('volume_change', models.CharField(blank=True, max_length=100, null=True)),
                ('circulating_supply', models.CharField(blank=True, max_length=100, null=True)),
                ('total_supply', models.CharField(blank=True, max_length=100, null=True)),
                ('diluted_market_cap', models.CharField(blank=True, max_length=100, null=True)),
                ('job_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper.job')),
            ],
        ),
        migrations.CreateModel(
            name='Official_Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('scraping_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.scrapping_details')),
            ],
        ),
        migrations.CreateModel(
            name='Contracts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('scraping_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.scrapping_details')),
            ],
        ),
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('scraping_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scraper.scrapping_details')),
            ],
        ),
    ]
